[package]
name = "dplang"
version = "0.4.0"
edition = "2021"

[dependencies]
rust_decimal = "1.33"
csv = "1.3"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.23.0"
